name = "OceanPlot"
uuid = "5b812ae1-0d5a-57ac-b54f-5a05511cf0ee"
version = "0.1.0"

[deps]
DIVAnd = "efc8151c-67de-5a8f-9a35-d8f54746ae9d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"

[extensions]
FFMPEGExt = "FFMPEG"

[compat]
DIVAnd = "2"
FFMPEG = "0.4"
MAT = "0.6, 0.7, 0.8, 0.9, 0.10"
NCDatasets = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14"
PyCall = "1"
PyPlot = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
